config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/about", to: "pages#about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check



  # Defines the root path route ("/")
  # root "posts#index"
  resources :treehouses, only: [ :index, :show, :new, :create ] do
    resources :bookings, only: [ :new, :create]
  end

  resources :bookings, only: [:index, :show, :destroy] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :treehouse
  belongs_to :user
  has_one :review, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/treehouse.rb
class Treehouse < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings
  has_one_attached :photo
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
  include PgSearch::Model
  pg_search_scope :search_by_name_and_location,
  against: [ :name, :location ],
  using: {
    tsearch: { prefix: true }
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :treehouses
  has_many :bookings
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # a boolean can be used to identify if the user is a host or not.
  # I'll work out how to implement that later
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.where(user: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @treehouse = Treehouse.find(params[:treehouse_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @treehouse = Treehouse.find(params[:treehouse_id])
    @booking.user = current_user
    @booking.treehouse = @treehouse
    @booking.save
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_treehouse
    @treehouse = Treehouse.find(params[:treehouse_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :guests)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  # update to include index, show

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @booking = Booking.find(params[:booking_id])
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking
    if @review.save
      redirect_to treehouse_path(@booking.treehouse)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @reviews = review.where(params[:booking_id])
  end

  private

  # def set_treehouse
  #   @treehouse = Treehouse.find(params[:treehouse_id])
  # end

  def review_params
    params.require(:review).permit(:title, :content, :rating)
  end
end

app/controllers/treehouses_controller.rb
class TreehousesController < ApplicationController

  def index
    @treehouses = Treehouse.all
    if params[:query].present?
      sql_subquery = <<~SQL
        treehouses.name @@ :query
        OR treehouses.location @@ :query
      SQL
      @treehouses = @treehouses.where(sql_subquery, query: params[:query])
    end
  end

  def show
    @treehouse = Treehouse.find(params[:id])
    @marker = {lat: "", lng: ""}
    @marker[:lat] = @treehouse.geocode[0]
    @marker[:lng] = @treehouse.geocode[1]
    @bookings = @treehouse.bookings
    @reviews = @treehouse.reviews
    @booking = Booking.new


  end

  def new
    @treehouse = Treehouse.new
  end

  def create
    @treehouse = Treehouse.new(treehouse_params)
    @treehouse.user = current_user
    @treehouse.save
    redirect_to treehouse_path(@treehouse)
  end

  private

  def treehouse_params
    params.require(:treehouse).permit(:name, :location, :tree_type, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1611990811697-204c28796f52?q=80&w=1742&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)">
  My Bookings:
</div>

 <div class="top-buttons">
  <button class="btn btn-success" role="button"><%= link_to "Back to Treehouses", treehouses_path, class: "text-decoration-none text-white" %>
  </button>
  </div>

<div class="container">

  <% @bookings.each do |booking| %>
    <div class="booking-card">
    <div class="booking-card-info">
    <p>Congratulations, your booking to <strong><%= booking.treehouse.name.capitalize %></strong> is secured!</p>
    <p>You will be staying:</p>
    <p>From: <%= booking.start_date%> Until: <%= booking.end_date%></p>
    <p> </p>
    <p><%= link_to "Delete",
      booking_path(booking),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-success"
    %></p>
    <%= link_to "Add Review", new_booking_review_path(booking), class: "btn btn-success" %>
    </div>
      <div class="booking-card-img">
        <img src="https://media.istockphoto.com/id/1371148606/vector/confirmed-rubber-business-stamp.jpg?s=612x612&w=0&k=20&c=wAtWMe_1n88w2l9iU47vex22x2Lk24echF2u9zePhC0=" alt="">
      </div>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<h2><%= @treehouse.name %></h2>
<p>£<%= @treehouse.price %></p>

<%= simple_form_for [@treehouse, @booking] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.submit "Submit Booking", class: "btn btn-primary" %>
<% end %>

app/views/bookings/show.html.erb
<h1>Your Booking</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbTemplate</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body class="bg-green">
    <%= render "shared/navbar" %>
    <%# <p class="notice"><%= notice %>
    <%# <p class="alert"><%= alert %>
    <%= render "shared/flashes" %>
    <%= yield %>

    <footer>
    <ul>
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
  <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
</svg>
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
  <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334q.002-.211-.006-.422A6.7 6.7 0 0 0 16 3.542a6.7 6.7 0 0 1-1.889.518 3.3 3.3 0 0 0 1.447-1.817 6.5 6.5 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.32 9.32 0 0 1-6.767-3.429 3.29 3.29 0 0 0 1.018 4.382A3.3 3.3 0 0 1 .64 6.575v.045a3.29 3.29 0 0 0 2.632 3.218 3.2 3.2 0 0 1-.865.115 3 3 0 0 1-.614-.057 3.28 3.28 0 0 0 3.067 2.277A6.6 6.6 0 0 1 .78 13.58a6 6 0 0 1-.78-.045A9.34 9.34 0 0 0 5.026 15"/>
</svg>
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
      <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
    </svg>
    </ul>
      <small>
        Copyright © 2024 Treehouse Retreats. All Rights Reserved.
      </small>
    </footer>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is my about page!</h1>

app/views/pages/home.html.erb
<div class="card-category-home" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1618767689160-da3fb810aad7?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)">
    <h1 class="company-name text-center my-3" style="font-size: 100px">Treehouse Retreats</h1>
</div>

<%# <div class="container">
  <div class="row justify-content-center w100">
    <h1 class="company-name text-center my-3">Treehouse Retreats</h1>
    <img src="https://images.unsplash.com/photo-1618767689160-da3fb810aad7?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" class="rounded my-1">
  </div>
</div> %>

<div class="container my-3">
  <div class="row justify-content-center">
    <h2 style="font-size: 50px">🌳Welcome to Treehouse Retreats! <br> Where dreams reach new heights!🌳</h2>
    <%# <p>Escape the ordinary and elevate your getaway with our enchanting treehouse rentals.</p> %>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: treehouses_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search Our Treehouses"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-success text-decoration-none text-white" %>
    <% end %>
  </div>

<%# # button to see all treehouses %>
<div class="d-flex justify-content-center">
  <button class="btn btn-success" role="button"><%= link_to "See Our Treehouses", treehouses_path, class: "text-decoration-none text-white"  %></div>
</div>

app/views/reviews/new.html.erb
<div class="container mt-3">
<%= simple_form_for [@booking, @review] do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "Submit review", class: "btn btn-success" %>
<% end %>
</div>

app/views/shared/_booking_form.html.erb
<div data-controller="booking-form" data-booking-form-price-value="<%= @treehouse.price %>">
  <%= simple_form_for [@treehouse, @booking] do |f| %>
    <%= f.input :guests %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.submit "Submit Booking", class: "btn btn-success" %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon border-bottom">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "treehouse_logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <%#<li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          <%# </li> %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "app-icon-person.png", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/treehouses/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1611990811697-204c28796f52?q=80&w=1742&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)">
  Our Treehouses
</div>

<div class="top-buttons">
<button class="btn btn-success" role="button"><%= link_to "Add Your Treehouse", new_treehouse_path, class: "text-decoration-none text-white" %></button>
<button class="btn btn-success" role="button"><%= link_to "My Bookings", bookings_path, class: "text-decoration-none text-white" %></button>
<button class="btn btn-success" role="button"><%= link_to "See Our Treehouses", treehouses_path, class: "text-decoration-none text-white"  %></div>

</div>

<div class="row justify-content-center">
  <div class="col-sm-8 my-3">
    <%= form_with url: treehouses_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Search Our Treehouses"
        %>
      <%= submit_tag "Search", name: "", class: "btn btn-success text-decoration-none text-white" %>
    <% end %>
  </div>




<div class="treehouse-container">
  <% @treehouses.each do |tree| %>
  <div class="treehouse-card">
    <%= cl_image_tag tree.photo.key, height: 300, width: 400, crop: :fill %>

      <div class="treehouse-card-info mx-4 mt-2">
        <div>
          <h3 class="mb-0"><%= tree.name.capitalize %></h3>
          <p class="mb-0">Type of Tree: <%= tree.tree_type.capitalize %></p>
          <p class="mb-0">Rating: <%= tree.rating %> 🌳</p>
        </div>
        <div class="price mx-4">
          <p>£<%= tree.price %> per night</p>
          <p class="btn btn-success" role="button"><%= link_to "Explore this Treehouse", treehouse_path(tree), class: "text-decoration-none text-white" %></p>
        </div>
      </div>
  </div>
  <% end %>
</div>

app/views/treehouses/new.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1611990811697-204c28796f52?q=80&w=1742&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D)">
  New Treehouse:
</div>

 <div class="top-buttons">
  <button class="btn btn-success" role="button"><%= link_to "Back to Treehouses", treehouses_path, class: "text-decoration-none text-white" %>
  </button>
  </div>

<br>
<div class="container">
<%= simple_form_for [@treehouse] do |f| %>
    <%= f.input :name %>
    <%= f.input :location %>
    <%= f.input :description %>
    <%= f.input :tree_type %>
    <%= f.input :price %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Submit review", class: "btn btn-success" %>
<% end %>
</div>

app/views/treehouses/show.html.erb
<div class="show-page" style="position: relative;">

  <div class="top-buttons mb-3">
  <button class="btn btn-success" role="button"><%= link_to "Back to Treehouses", treehouses_path, class: "text-decoration-none text-white" %>
  </button>
  </div>



    <div class="form-booking position-fixed top-10 end-0 me-5 btn-lg" data-controller="toggle">
      <button data-action="click->toggle#fire" class="btn btn-success text-decoration-none text-white" >Book now!</button>
      <div data-toggle-target="element" class="d-none">
        <%= render "shared/booking_form" %>
      </div>
    </div>

<div class="show-container">


  <h1 class="show-title"><%= @treehouse.name.capitalize %></h1>


  <div class="show-treehouse w-100">
    <img id="left" src="https://images.unsplash.com/photo-1573790285658-87d7586eec7d?q=80&w=3387&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="">
    <div class="righthand">
      <div>
        <img id="topright" src="https://plus.unsplash.com/premium_photo-1664047696174-72d3d84e6d5e?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8dHJlZWhvdXNlfGVufDB8fDB8fHww" alt="">
        <img id="bottomright" src="https://images.unsplash.com/photo-1615354310157-c78b1be66eed?w=400&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dHJlZWhvdXNlfGVufDB8fDB8fHww" alt="">
      </div>
    </div>
  </div>



  <div class="info-and-booking">

    <ul class="list-inline d-flex justify-content-center w-100">

        <li class="list-inline-item"><%= @treehouse.guests %> guests  .  </li>
        <li class="list-inline-item"><%= @treehouse.tree_type.capitalize %> tree  .  </li>
        <li class="list-inline-item">Location: <%= @treehouse.location %>  .  </li>
        <li class="list-inline-item">£ <%= @treehouse.price %> per night  .  </li>
        <li class="list-inline-item"><a href="#reviews"><%= @treehouse.reviews.count %> Reviews</a></li>
    </ul>

  </div>

  <h2>Description</h2>
  <p><%= @treehouse.description %></p>

<h2>Where you will be staying:</h2>
<p>You will be nested in the heart of <%= @treehouse.location %>:</p>

<div style="width: 100%; height: 600px;"
  data-controller="map"
  data-map-marker-value="<%= @marker.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>




<h2 class="mt-4">Reviews:</h2>
  <div class="review-container" id="reviews">
    <% @reviews.each do |review| %>
      <div class="review-card">
        <div class="review-number">
          <div>
          <p><%= review.created_at.strftime("Created on %m/%d/%Y") %></p>
          </div>
          <div>
            <h3><%= review.rating %></h3>
          </div>
        </div>
        <div class="review-text">
          <h3>''<%= review.title %>....</h3>
          <p><%= review.content %>''</p>
        </div>
      </div>
    <% end %>
  </div>

</div>

</div>